version: '3.8'

services:
  app:
    image: booking
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev

  db:
    image: h2
    ports:
      - "8082:8082"