spring.application.name=booking

spring.jpa.show-sql=true
spring.jpa.ddl-auto=create
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.format_sql=true

spring.datasource.ur=jdbc:h2:file:~/bookingdb;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.datasource.initialization-mode=always
spring.datasource.initialize=true
spring.sql.init.schema-locations=classpath:sql/schema.sql
spring.sql.init.data-locations=classpath:sql/data.sql

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.mvc.problem-details.enabled=true

springdoc.swagger-ui.displayRequestDuration=true
springdoc.show-examples=true

resilience4j.bulkhead.instances.rooms.maxConcurrentCalls=10
resilience4j.bulkhead.instances.rooms.maxWaitDuration=10ms


resilience4j.bulkhead.instances.space.maxThreadPoolSize=10
resilience4j.bulkhead.instances.space.coreThreadPoolSize=5
resilience4j.bulkhead.instances.space.queueCapacity=20
